import { Inter } from 'next/font/google';
import "./globals.css";
import Sessionwrapper from "./components/sessionwrapper";

// Using Inter font as it's more reliable with Vercel
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${inter.variable} font-sans antialiased`}>
        <Sessionwrapper>
        {children}
        </Sessionwrapper>
      </body>
     
    </html>
  );
}
